services:

  backend:
    build:
      context: ./backend

    container_name: tikfast-backend

    expose:
      - "3000"

    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: tikfast-nginx

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "8080:80"

    restart: unless-stopped